"""empty message

Revision ID: 138db5700d4d
Revises: 4f27677597b9
Create Date: 2022-02-11 13:40:44.320872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138db5700d4d'
down_revision = '4f27677597b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ongoing_proj', sa.Column('award_date', sa.Date(), nullable=True))
    op.add_column('ongoing_proj', sa.Column('cost_to_complete', sa.String(length=50), nullable=True))
    op.add_column('ongoing_proj', sa.Column('funding', sa.String(length=50), nullable=True))
    op.add_column('ongoing_proj', sa.Column('physical', sa.String(length=50), nullable=True))
    op.add_column('ongoing_proj', sa.Column('procurement', sa.String(length=50), nullable=True))
    op.add_column('ongoing_proj', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('ongoing_proj', sa.Column('status', sa.String(length=80), nullable=True))
    op.add_column('ongoing_proj', sa.Column('time_elapsed', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ongoing_proj', 'time_elapsed')
    op.drop_column('ongoing_proj', 'status')
    op.drop_column('ongoing_proj', 'remarks')
    op.drop_column('ongoing_proj', 'procurement')
    op.drop_column('ongoing_proj', 'physical')
    op.drop_column('ongoing_proj', 'funding')
    op.drop_column('ongoing_proj', 'cost_to_complete')
    op.drop_column('ongoing_proj', 'award_date')
    # ### end Alembic commands ###
