"""empty message

Revision ID: 3520b4bb3d29
Revises: 8e7691815f8b
Create Date: 2021-05-19 09:32:55.793058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3520b4bb3d29'
down_revision = '8e7691815f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('rank', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('date_app', sa.Date(), nullable=False),
    sa.Column('tele_no', sa.Integer(), nullable=False),
    sa.Column('leave_cat', sa.String(length=30), nullable=False),
    sa.Column('no_of_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('supp_info', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('mobile_no', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('days_proceed', sa.Integer(), nullable=False),
    sa.Column('effec_date', sa.Date(), nullable=False),
    sa.Column('resump_date', sa.Date(), nullable=False),
    sa.Column('outs_days', sa.Integer(), nullable=False),
    sa.Column('leave_status', sa.String(length=20), nullable=True),
    sa.Column('reasons', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_leave_status'), 'leave', ['leave_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_leave_status'), table_name='leave')
    op.drop_table('leave')
    # ### end Alembic commands ###
