"""empty message

Revision ID: 4f27677597b9
Revises: a433c5cce143
Create Date: 2022-02-11 12:02:07.271595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f27677597b9'
down_revision = 'a433c5cce143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_proj', sa.Column('award_date', sa.Date(), nullable=True))
    op.add_column('planned_proj', sa.Column('cost_to_complete', sa.String(length=50), nullable=True))
    op.add_column('planned_proj', sa.Column('funding', sa.String(length=50), nullable=True))
    op.add_column('planned_proj', sa.Column('physical', sa.String(length=50), nullable=True))
    op.add_column('planned_proj', sa.Column('procurement', sa.String(length=50), nullable=True))
    op.add_column('planned_proj', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('planned_proj', sa.Column('time_elapsed', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_proj', 'time_elapsed')
    op.drop_column('planned_proj', 'remarks')
    op.drop_column('planned_proj', 'procurement')
    op.drop_column('planned_proj', 'physical')
    op.drop_column('planned_proj', 'funding')
    op.drop_column('planned_proj', 'cost_to_complete')
    op.drop_column('planned_proj', 'award_date')
    # ### end Alembic commands ###
