"""empty message

Revision ID: 8e7691815f8b
Revises: 5dda4ff1c744
Create Date: 2021-05-17 11:02:52.518549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7691815f8b'
down_revision = '5dda4ff1c744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('reasons', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave', 'reasons')
    # ### end Alembic commands ###
