"""empty message

Revision ID: a433c5cce143
Revises: 0dad6173ff36
Create Date: 2022-02-09 13:02:27.018554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a433c5cce143'
down_revision = '0dad6173ff36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resurfacing')
    op.drop_table('regravelling')
    op.drop_table('partialreconstruction')
    op.drop_table('resealing')
    op.drop_table('contract')
    op.drop_table('decongestion')
    op.drop_table('supply')
    op.drop_table('repairs')
    op.drop_table('upgrading')
    op.drop_table('asphalticoverlay')
    op.drop_table('construction')
    op.drop_table('rehabilitation')
    op.drop_table('preconstruction')
    op.drop_table('grading')
    op.add_column('planned_proj', sa.Column('status', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_proj', 'status')
    op.create_table('grading',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='grading_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('preconstruction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='preconstruction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rehabilitation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rehabilitation_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('construction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.TEXT(), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='construction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('asphalticoverlay',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='asphalticoverlay_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('upgrading',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='upgrading_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('repairs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='repairs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('supply',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='supply_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('decongestion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='decongestion_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('contract',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='contract_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resealing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='resealing_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('partialreconstruction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='partialreconstruction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('regravelling',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='regravelling_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resurfacing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('project', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('length', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contractor', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('date_commenced', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('contract_sum', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amt_to_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('video_title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('video_link', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='resurfacing_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
