"""Add name and category to Gallery

Revision ID: b42d27ea69fa
Revises: c94e71e2d7c2
Create Date: 2026-01-15 16:09:01.658291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b42d27ea69fa'
down_revision = 'c94e71e2d7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery', 'upload_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('upload_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('completed_proj', sa.Column('contract_duration_m', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('int_on_delay_pay', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('ori_date_completion', sa.DATE(), nullable=True))
    op.add_column('completed_proj', sa.Column('sup_agency', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('contract_duration', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('ori_contract_sum', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('time_elapsed_p', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('variations', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('pay_made_to_date', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('comment_ibfk_1_idx', 'comment', ['post_id'], unique=False)
    op.create_table('csvjson',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', mysql.TEXT(), nullable=True),
    sa.Column('category', mysql.TEXT(), nullable=True),
    sa.Column('project', mysql.TEXT(), nullable=True),
    sa.Column('length', mysql.TEXT(), nullable=True),
    sa.Column('contractor', mysql.TEXT(), nullable=True),
    sa.Column('award_date', mysql.TEXT(), nullable=True),
    sa.Column('date_commenced', mysql.TEXT(), nullable=True),
    sa.Column('ori_date_completion', mysql.TEXT(), nullable=True),
    sa.Column('revised_date', mysql.TEXT(), nullable=True),
    sa.Column('date_completed', mysql.TEXT(), nullable=True),
    sa.Column('ori_contract_sum', mysql.TEXT(), nullable=True),
    sa.Column('variations', mysql.TEXT(), nullable=True),
    sa.Column('contract_sum', mysql.TEXT(), nullable=True),
    sa.Column('amt_to_date', mysql.TEXT(), nullable=True),
    sa.Column('int_on_delay_pay', mysql.TEXT(), nullable=True),
    sa.Column('pay_made_to_date', mysql.TEXT(), nullable=True),
    sa.Column('sup_agency', mysql.TEXT(), nullable=True),
    sa.Column('funding', mysql.TEXT(), nullable=True),
    sa.Column('procurement', mysql.TEXT(), nullable=True),
    sa.Column('contract_duration', mysql.TEXT(), nullable=True),
    sa.Column('contract_duration_m', mysql.TEXT(), nullable=True),
    sa.Column('physical', mysql.TEXT(), nullable=True),
    sa.Column('time_elapsed', mysql.TEXT(), nullable=True),
    sa.Column('time_elapsed_p', mysql.TEXT(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.TEXT(), nullable=True),
    sa.Column('image_one', mysql.TEXT(), nullable=True),
    sa.Column('image_two', mysql.TEXT(), nullable=True),
    sa.Column('video_title', mysql.TEXT(), nullable=True),
    sa.Column('video_link', mysql.TEXT(), nullable=True),
    sa.Column('video_description', mysql.TEXT(), nullable=True),
    sa.Column('video_thumb', mysql.TEXT(), nullable=True),
    sa.Column('uploaded_time', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
