"""empty message

Revision ID: c22cf54cdbef
Revises: 138db5700d4d
Create Date: 2022-02-11 13:55:38.835056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22cf54cdbef'
down_revision = '138db5700d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_proj', sa.Column('award_date', sa.Date(), nullable=True))
    op.add_column('completed_proj', sa.Column('cost_to_complete', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('funding', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('physical', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('procurement', sa.String(length=50), nullable=True))
    op.add_column('completed_proj', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('completed_proj', sa.Column('status', sa.String(length=80), nullable=True))
    op.add_column('completed_proj', sa.Column('time_elapsed', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_proj', 'time_elapsed')
    op.drop_column('completed_proj', 'status')
    op.drop_column('completed_proj', 'remarks')
    op.drop_column('completed_proj', 'procurement')
    op.drop_column('completed_proj', 'physical')
    op.drop_column('completed_proj', 'funding')
    op.drop_column('completed_proj', 'cost_to_complete')
    op.drop_column('completed_proj', 'award_date')
    # ### end Alembic commands ###
