"""empty message

Revision ID: c94e71e2d7c2
Revises: c22cf54cdbef
Create Date: 2022-02-11 14:00:06.467691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94e71e2d7c2'
down_revision = 'c22cf54cdbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_proj', sa.Column('revised_date', sa.Date(), nullable=True))
    op.add_column('completed_proj', sa.Column('revised_sum', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_proj', 'revised_sum')
    op.drop_column('completed_proj', 'revised_date')
    # ### end Alembic commands ###
