from datetime import datetime, date
from trial import db, bcrypt
from trial.models import User
staff = {
    "staff_list": [
        {
            "Ref No": "PF/O.627",
            "ACC-GEN Staff No": "642909",
            "SSF_NO" : "F158005850030",
            "NAME" : "OBENG EDMUND",
            "BIRTH DATE" : datetime.strptime("25-05-1980", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("03-08-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-03-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/O.650",
            "ACC-GEN Staff No": "839577",
            "SSF_NO" : "40120111315",
            "NAME" : "OSEI-ASAMOAH SAMUEL",
            "BIRTH DATE" : datetime.strptime("06-01-1987", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("04-07-2011", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-08-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/560",
            "ACC-GEN Staff No": "NULL",
            "SSF_NO" : "60120130681",
            "NAME" : "DANSO FRED GYIMAH ",
            "BIRTH DATE" : datetime.strptime("11-04-1987", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("02-07-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-08-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/S.303",
            "ACC-GEN Staff No": "705007",
            "SSF_NO" : "C018009110173",
            "NAME" : "SARFO SAMUEL",
            "BIRTH DATE" : datetime.strptime("11-09-1980", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("17-12-2008", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-12-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/A.2464",
            "ACC-GEN Staff No": "714470",
            "SSF_NO" : "B108206280010",
            "NAME" : "AMISSAH JOHN ESSAH",
            "BIRTH DATE" : datetime.strptime("28-08-1981", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("16-03-2009", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/F.161",
            "ACC-GEN Staff No": "910538",
            "SSF_NO" : "C018612060030",
            "NAME" : "FIAGBEY GODSWILL ELORM",
            "BIRTH DATE" : datetime.strptime("06-12-1986", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR ENGINEER (GEODETIC)",
            "DATE_ENGAGED" : datetime.strptime("01-11-2012", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-04-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "A.2378",
            "ACC-GEN Staff No": "17308",
            "SSF_NO" : "F117007280012",
            "NAME" : "ADDAE CLEMENT",
            "BIRTH DATE" : datetime.strptime("28-07-1970", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL QUANTITY SURVEYOR",
            "DATE_ENGAGED" : datetime.strptime("01-11-2001", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-02-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/K.518",
            "ACC-GEN Staff No": "720660",
            "SSF_NO" : "G088204040046",
            "NAME" : "KORSAH CHARLOTTE",
            "BIRTH DATE" : datetime.strptime("04-04-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "QUANTITY SURVEYOR",
            "DATE_ENGAGED" : datetime.strptime("01-01-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/F.159",
            "ACC-GEN Staff No": "889695",
            "SSF_NO" : "D0178803080012",
            "NAME" : "FRANCE EBENEZER NII DJAN",
            "BIRTH DATE" : datetime.strptime("08-03-1978", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL INTERNAL AUDITOR",
            "DATE_ENGAGED" : datetime.strptime("20-02-2012", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-03-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "A.2230",
            "ACC-GEN Staff No": "28309",
            "SSF_NO" : "J046109150022",
            "NAME" : "ASEMITENG PAULINA",
            "BIRTH DATE" : datetime.strptime("15-09-1962", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "CHIEF ACCOUNTANT",
            "DATE_ENGAGED" : datetime.strptime("01-06-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2020", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "PF/F.150",
            "ACC-GEN Staff No": "643670",
            "SSF_NO" : "F035907010313",
            "NAME" : "FORDJOUR POKU ENOCH",
            "BIRTH DATE" : datetime.strptime("13-10-1980", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "ACCOUNTANT",
            "DATE_ENGAGED" : datetime.strptime("04-09-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "NULL",
            "ACC-GEN Staff No": "1373659",
            "SSF_NO" : "A169104110084",
            "NAME" : "SEKUM ANTOINNETTE",
            "BIRTH DATE" : datetime.strptime("11-04-1991", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "ACCOUNTANT",
            "DATE_ENGAGED" : datetime.strptime("06-11-2020", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("06-11-2020", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "T.298",
            "ACC-GEN Staff No": "17076",
            "SSF_NO" : "F016810290019",
            "NAME" : "TURKSON MICHAEL CYRUS",
            "BIRTH DATE" : datetime.strptime("29-10-1968", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF ADMINISTRATIVE OFFICER",
            "DATE_ENGAGED" : datetime.strptime("09-01-2003", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-02-2016", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/J.15",
            "ACC-GEN Staff No": "26331",
            "SSF_NO" : "H276211100020",
            "NAME" : "JARO MARY ELIZABETH",
            "BIRTH DATE" : datetime.strptime("11-11-1962", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "CHIEF PERSONNEL OFFICER",
            "DATE_ENGAGED" : datetime.strptime("01-01-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "O. 464",
            "ACC-GEN Staff No": "29493",
            "SSF_NO" : "40302853",
            "NAME" : "OFORIWAH COMFORT",
            "BIRTH DATE" : datetime.strptime("02-02-1962", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "SENIOR PRIVATE  SECRETARY",
            "DATE_ENGAGED" : datetime.strptime("01-08-1981", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "F.147",
            "ACC-GEN Staff No": "92423",
            "SSF_NO" : "F066402030028",
            "NAME" : "FOSU GYEABOUR  MONICA",
            "BIRTH DATE" : datetime.strptime("02-09-1964", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "PRIVITE SECRETARY",
            "DATE_ENGAGED" : datetime.strptime("01-05-1984", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/O.660",
            "ACC-GEN Staff No": "802772",
            "SSF_NO" : "E028006110038",
            "NAME" : "OHENE-TAKYI JACOB",
            "BIRTH DATE" : datetime.strptime("11-06-1980", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL SUPPLY OFFICER",
            "DATE_ENGAGED" : datetime.strptime("01-12-2011", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-04-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "I.40",
            "ACC-GEN Staff No": "671735",
            "SSF_NO" : "D056810060013",
            "NAME" : "IDAD ABDUL MUMUNI",
            "BIRTH DATE" : datetime.strptime("26-06-1968", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL INVESTIGATION OFFICER",
            "DATE_ENGAGED" : datetime.strptime("19-11-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-12-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "B.377",
            "ACC-GEN Staff No": "18471",
            "SSF_NO" : "40194383",
            "NAME" : "BEMPONG ERNEST AGYEPONG",
            "BIRTH DATE" : datetime.strptime("21-08-1961", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF TECHNICIAN ENGINEER (QTY)",
            "DATE_ENGAGED" : datetime.strptime("01-10-1981", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-08-2003", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "O.574",
            "ACC-GEN Staff No": "13391",
            "SSF_NO" : "C0166707040199",
            "NAME" : "OKPOTI JAMES TETTEH",
            "BIRTH DATE" : datetime.strptime("04-07-1966", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "ASSISTANT CHIEF TECHNICIAN ENGINEER05-04-1989",
            "DATE_ENGAGED" : datetime.strptime("05-04-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/M.448",
            "ACC-GEN Staff No": "924531",
            "SSF_NO" : "K018204110030",
            "NAME" : "MOOMIN SEIDU NURIDEEN",
            "BIRTH DATE" : datetime.strptime("11-02-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL TECHNICIAN ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("05-07-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-08-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/C.97",
            "ACC-GEN Staff No": "NULL",
            "SSF_NO" : "NULL",
            "NAME" : "CRENTSIL NANCY",
            "BIRTH DATE" : datetime.strptime("04-09-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "PRINCIPAL TECHNICIAN ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("10-06-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-04-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "O.651",
            "ACC-GEN Staff No": "843458",
            "SSF_NO" : "NULL",
            "NAME" : "OBOBI EBENEZER KAFUI",
            "BIRTH DATE" : datetime.strptime("24-06-1984", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR TECHNICIAN ENGINEER (CIVIL)",
            "DATE_ENGAGED" : datetime.strptime("18-07-2011", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-12-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "NULL",
            "ACC-GEN Staff No": "11964",
            "SSF_NO" : "C018208240557",
            "NAME" : "ADOTEY HENRY KPAKPO",
            "BIRTH DATE" : datetime.strptime("24-08-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR TECHNICIAN ENGINEER (QTY)",
            "DATE_ENGAGED" : datetime.strptime("30-11-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("11-12-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF. O - 569",
            "ACC-GEN Staff No": "18559",
            "SSF_NO" : "J056112290015",
            "NAME" : "ODURO ADU KWAKU",
            "BIRTH DATE" : datetime.strptime("09-12-1961", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "ASSISTANT CHIEF TECHNICAL OFFICER",
            "DATE_ENGAGED" : datetime.strptime("01-07-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-07-2011", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "A.2237",
            "ACC-GEN Staff No": "18193",
            "SSF_NO" : "C016502060213",
            "NAME" : "ADJAPONG ROBERT JOHNNY",
            "BIRTH DATE" : datetime.strptime("06-02-1965", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF TECHNICAL OFFR. (MATS)",
            "DATE_ENGAGED" : datetime.strptime("15-01-1990", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2014", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/C.94",
            "ACC-GEN Staff No": "661111",
            "SSF_NO" : "FO18101020045",
            "NAME" : "CHABTIR GENEVIEVE",
            "BIRTH DATE" : datetime.strptime("02-01-1981", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "ASSISTANT CHIEF TECHNICAL OFFICER (ROAD MAINTENANCE)",
            "DATE_ENGAGED" : datetime.strptime("13-09-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-09-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/M.429",
            "ACC-GEN Staff No": "770778",
            "SSF_NO" : "F018504090134",
            "NAME" : "MANU PAUL",
            "BIRTH DATE" : datetime.strptime("28-08-1981", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL TECHNICAL OFFICER",
            "DATE_ENGAGED" : datetime.strptime("02-07-2010", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2020", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "A.2524",
            "ACC-GEN Staff No": "843344",
            "SSF_NO" : "E018210040033",
            "NAME" : "AMANOR STEPHEN",
            "BIRTH DATE" : datetime.strptime("10-05-1984", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL TECHNICAL OFFICER  ( RD MTCE)",
            "DATE_ENGAGED" : datetime.strptime("21-07-2011", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-08-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/A.2591",
            "ACC-GEN Staff No": "972050",
            "SSF_NO" : "C019205290123",
            "NAME" : "ARTHUR ANITA",
            "BIRTH DATE" : datetime.strptime("29-05-1992", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "TECHNICAL OFFICER GD I",
            "DATE_ENGAGED" : datetime.strptime("09-12-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/M.449",
            "ACC-GEN Staff No": "971683",
            "SSF_NO" : "C018812110367",
            "NAME" : "MACAULEY JENNIFER",
            "BIRTH DATE" : datetime.strptime("11-12-1988", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "TECHNICAL OFFICER GD I",
            "DATE_ENGAGED" : datetime.strptime("12-12-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/O.676",
            "ACC-GEN Staff No": "971756",
            "SSF_NO" : "C039105290014",
            "NAME" : "ODOOM THEOPHILUS",
            "BIRTH DATE" : datetime.strptime("29-05-1991", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "TECHNICAL OFFICER GRADE I",
            "DATE_ENGAGED" : datetime.strptime("04-12-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/A.2595",
            "ACC-GEN Staff No": "NULL",
            "SSF_NO" : "F159004260018",
            "NAME" : "AGYARE SAMUEL GYEKYE",
            "BIRTH DATE" : datetime.strptime("26-04-1992", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "TECHNICAL OFFICER GD I",
            "DATE_ENGAGED" : datetime.strptime("16-12-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/A.2582",
            "ACC-GEN Staff No": "971697",
            "SSF_NO" : "F049302070025",
            "NAME" : "ADJANOR REGINA",
            "BIRTH DATE" : datetime.strptime("07-02-1993", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "TECHNICAL OFFICER GD I (S&D)",
            "DATE_ENGAGED" : datetime.strptime("09-12-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "D. 453",
            "ACC-GEN Staff No": "92288",
            "SSF_NO" : "F016507100084",
            "NAME" : "DANQUAH BOAKYE HENRIETTA",
            "BIRTH DATE" : datetime.strptime("10-07-1965", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "STERNOGRAPHER",
            "DATE_ENGAGED" : datetime.strptime("14-08-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-11-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/A.1705",
            "ACC-GEN Staff No": "796594",
            "SSF_NO" : "F019004210022",
            "NAME" : "AMANABA EMELIA",
            "BIRTH DATE" : datetime.strptime("21-04-1990", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CLERK GRADE I",
            "DATE_ENGAGED" : datetime.strptime("01-09-2010", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-10-2014", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "PF/A.2577",
            "ACC-GEN Staff No": "927174",
            "SSF_NO" : "F188907100024",
            "NAME" : "ACHEAMPONG DORIS",
            "BIRTH DATE" : datetime.strptime("10-07-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "SENIOR CLERK",
            "DATE_ENGAGED" : datetime.strptime("25-09-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-10-2016", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "D. 51",
            "ACC-GEN Staff No": "14012",
            "SSF_NO" : "37664265",
            "NAME" : "DONKOR ROBERT",
            "BIRTH DATE" : datetime.strptime("10-02-1962", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR DRIVER",
            "DATE_ENGAGED" : datetime.strptime("01-08-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-06-1997", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "M.M.U. II",

        },
        {
            "Ref No": "B.425",
            "ACC-GEN Staff No": "14582",
            "SSF_NO" : "NULL",
            "NAME" : "BAFFOUR ANTWI CLEMENT",
            "BIRTH DATE" : datetime.strptime("04-02-1963", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR DRIVER",
            "DATE_ENGAGED" : datetime.strptime("11-11-1979", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-12-2010", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "MR/O.158",
            "ACC-GEN Staff No": "4756",
            "SSF_NO" : "40952806",
            "NAME" : "OSEI SOLOMON ",
            "BIRTH DATE" : datetime.strptime("06-04-1965", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL TRADESMAN",
            "DATE_ENGAGED" : datetime.strptime("30-05-1983", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2014", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "A.2429",
            "ACC-GEN Staff No": "672977",
            "SSF_NO" : "C016412020116",
            "NAME" : "ALLOTEY NII EMMANUEL",
            "BIRTH DATE" : datetime.strptime("25-12-1964", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "DRIVER GRADE I",
            "DATE_ENGAGED" : datetime.strptime("01-11-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-10-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/A.1677",
            "ACC-GEN Staff No": "728573",
            "SSF_NO" : "F017408280219",
            "NAME" : "ANTWI YAW",
            "BIRTH DATE" : datetime.strptime("28-08-1974", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "DRIVER GRADE I",
            "DATE_ENGAGED" : datetime.strptime("01-04-2009", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-04-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/A.1688",
            "ACC-GEN Staff No": "769733",
            "SSF_NO" : "F017412230178",
            "NAME" : "ASARE-KWAFFO KENNETH",
            "BIRTH DATE" : datetime.strptime("23-12-1974", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SENIOR DRIVER",
            "DATE_ENGAGED" : datetime.strptime("01-06-2009", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-06-2020", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/S.295",
            "ACC-GEN Staff No": "912123",
            "SSF_NO" : "F017505100318",
            "NAME" : "SARPONG FRANCIS",
            "BIRTH DATE" : datetime.strptime("03-05-1975", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "DRIVER GD.I",
            "DATE_ENGAGED" : datetime.strptime("21-11-2012", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "B. 486",
            "ACC-GEN Staff No": "927317",
            "SSF_NO" : "F01771240153",
            "NAME" : "BOAMPONG JOSEPH",
            "BIRTH DATE" : datetime.strptime("24-11-1977", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "DRIVER GD.I",
            "DATE_ENGAGED" : datetime.strptime("22-08-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-09-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/A.1753",
            "ACC-GEN Staff No": "927308",
            "SSF_NO" : "C018204010894",
            "NAME" : "AMOABENG GEORGE",
            "BIRTH DATE" : datetime.strptime("01-04-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "DRIVER GRADE II",
            "DATE_ENGAGED" : datetime.strptime("12-09-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-09-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/D.554",
            "ACC-GEN Staff No": "912131",
            "SSF_NO" : "F118207150050",
            "NAME" : "DOKU ISAAC",
            "BIRTH DATE" : datetime.strptime("24-07-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "DRIVER GD II",
            "DATE_ENGAGED" : datetime.strptime("15-12-2012", "%d-%m-%Y").strftime("%Y-%m-%d"), 
            "PRES_APPT": datetime.strptime("01-01-2013", "%d-%m-%Y").strftime("%Y-%m-%d"), #ERROR
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "A. 1342",
            "ACC-GEN Staff No": "14692",
            "SSF_NO" : "F016108070032",
            "NAME" : "ATTIPOE HOPE",
            "BIRTH DATE" : datetime.strptime("04-08-1961", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL TRADESMAN (MECH.)",
            "DATE_ENGAGED" : datetime.strptime("10-10-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-12-2010", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "A. 1127",
            "ACC-GEN Staff No": "29477",
            "SSF_NO" : "B016312190016",
            "NAME" : "ABRAHAM MARK EKOW",
            "BIRTH DATE" : datetime.strptime("19-12-1963", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL TRADESMAN (AUTO)",
            "DATE_ENGAGED" : datetime.strptime("01-08-1981", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("02-06-2009", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/K.572",
            "ACC-GEN Staff No": "838743",
            "SSF_NO" : "NULL",
            "NAME" : "KWARKO BEATRICE",
            "BIRTH DATE" : datetime.strptime("20-08-1983", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "SENIOR TRADESMAN (COOK)",
            "DATE_ENGAGED" : datetime.strptime("09-09-2010", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-06-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "MMU.II",
        
        },
        {
            "Ref No": "Y. 30",
            "ACC-GEN Staff No": "5014",
            "SSF_NO" : "37449139",
            "NAME" : "YEBOAH ANDREWS",
            "BIRTH DATE" : datetime.strptime("08-02-1963", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL SECURITY GUARD",
            "DATE_ENGAGED" : datetime.strptime("01-03-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "MR/A.1093",
            "ACC-GEN Staff No": "23693",
            "SSF_NO" : "47813787",
            "NAME" : "ANARFI ERIC OPOKU",
            "BIRTH DATE" : datetime.strptime("13-06-1967", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "GATE CHECKER GRADE II",
            "DATE_ENGAGED" : datetime.strptime("16-09-1988", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-1994", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "Q.136",
            "ACC-GEN Staff No": "672022",
            "SSF_NO" : "NULL",
            "NAME" : "QUAYEFIO DANIEL",
            "BIRTH DATE" : datetime.strptime("20-08-1979", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL SECURITY GUARD",
            "DATE_ENGAGED" : datetime.strptime("05-11-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-09-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "BEKWAI",
        
        },
        {
            "Ref No": "MR/A.1733",
            "ACC-GEN Staff No": "905952",
            "SSF_NO" : "F017803270179",
            "NAME" : "ACHANA JAMES KOJO",
            "BIRTH DATE" : datetime.strptime("27-03-1978", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SECURITY GUARD GRADE I",
            "DATE_ENGAGED" : datetime.strptime("06-09-2012", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-10-2018", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "O.630",
            "ACC-GEN Staff No": "672331",
            "SSF_NO" : "F01820950129",
            "NAME" : "OPOKU PATRICIA",
            "BIRTH DATE" : datetime.strptime("05-09-1982", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "PRINCIPAL SECURITY GUARD",
            "DATE_ENGAGED" : datetime.strptime("01-11-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-12-2016", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/T.189",
            "ACC-GEN Staff No": "905961",
            "SSF_NO" : "NULL",
            "NAME" : "LUKUMANU TIJANI",
            "BIRTH DATE" : datetime.strptime("16-04-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SECURITY GUARD GRADE II",
            "DATE_ENGAGED" : datetime.strptime("06-09-2012", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-10-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/K.577",
            "ACC-GEN Staff No": "905963",
            "SSF_NO" : "F019106010116",
            "NAME" : "KARIKARI PATRICK",
            "BIRTH DATE" : datetime.strptime("01-06-1991", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "SECURITY GD II",
            "DATE_ENGAGED" : datetime.strptime("06-09-2012", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("11-10-2015", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "NULL",
            "ACC-GEN Staff No": "NULL",
            "SSF_NO" : "A046503090017",
            "NAME" : "ASARE-ANTWI KWAME",
            "BIRTH DATE" : datetime.strptime("01-01-2000", "%d-%m-%Y").strftime("%Y-%m-%d"), #null error in date
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL SECURITY GUARD",
            "DATE_ENGAGED" : datetime.strptime("01-11-2007", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-03-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "MAMPONG",

        },
        {
            "Ref No": "MR/A.1575",
            "ACC-GEN Staff No": "24485",
            "SSF_NO" : "42747139",
            "NAME" : "ABABIO OSEI STEPHEN",
            "BIRTH DATE" : datetime.strptime("21-03-1968", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "PRINCIPAL SECURITY GUARD",
            "DATE_ENGAGED" : datetime.strptime("01-12-1992", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-03-2017", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/D.542",
            "ACC-GEN Staff No": "12817",
            "SSF_NO" : "F066702150016",
            "NAME" : "DWUMAH YAW",
            "BIRTH DATE" : datetime.strptime("16-03-1962", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF HEADMAN",
            "DATE_ENGAGED" : datetime.strptime("15-05-1989", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2009", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "A.15",
            "ACC-GEN Staff No": "14839",
            "SSF_NO" : "F246109100018",
            "NAME" : "AMANKWAH KWAME",
            "BIRTH DATE" : datetime.strptime("10-09-1961", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF HEADMAN",
            "DATE_ENGAGED" : datetime.strptime("20-06-1983", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2004", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "S.170",
            "ACC-GEN Staff No": "13213",
            "SSF_NO" : "F036310020013",
            "NAME" : "OWUSU SEKYERE",
            "BIRTH DATE" : datetime.strptime("07-10-1962", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF HEADMAN",
            "DATE_ENGAGED" : datetime.strptime("01-12-1983", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2004", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",

        },
        {
            "Ref No": "K.562",
            "ACC-GEN Staff No": "12490",
            "SSF_NO" : "B106706010018",
            "NAME" : "ARTHUR KWAKU",
            "BIRTH DATE" : datetime.strptime("01-07-1967", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF HEADMAN (CONSV)",
            "DATE_ENGAGED" : datetime.strptime("01-08-1990", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2010", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "A.1200",
            "ACC-GEN Staff No": "12854",
            "SSF_NO" : "F036507010258",
            "NAME" : "ADOM JOSEPH",
            "BIRTH DATE" : datetime.strptime("18-04-1965", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "M",
            "JOB POSITION" : "CHIEF HEADMAN",
            "DATE_ENGAGED" : datetime.strptime("05-06-1984", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-01-2004", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        },
        {
            "Ref No": "MR/O.241",
            "ACC-GEN Staff No": "927177",
            "SSF_NO" : "D077807060023",
            "NAME" : "OPOKUA MARY",
            "BIRTH DATE" : datetime.strptime("07-11-1975", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "SEX" : "F",
            "JOB POSITION" : "HEADMAN LABOURER",
            "DATE_ENGAGED" : datetime.strptime("18-09-2013", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "PRES_APPT": datetime.strptime("01-10-2019", "%d-%m-%Y").strftime("%Y-%m-%d"),
            "DIVISION/STATION": "KUMASI",
        
        }
    ]
}

def update_staff(staff_list):
    entries = []
    passw = bcrypt.generate_password_hash('12345').decode('utf-8')
    def calc_age(date_born):
        today = date.today()
        return today.year - date_born.year - ((today.month, today.day) < (date_born.month, date_born.day))

    for staff in staff_list['staff_list']:
        birth_date = staff['BIRTH DATE']
        bday = datetime.strptime(birth_date, "%Y-%m-%d")
        staff_age = calc_age(bday)
        new_entry = User(ref_no=staff['Ref No'], acc_gen_no=staff['ACC-GEN Staff No'], ssf_no=staff['SSF_NO'],
                        name=staff['NAME'], dob=staff['BIRTH DATE'], sex=staff['SEX'],
                        job_pos=staff['JOB POSITION'], date_engaged=staff['DATE_ENGAGED'], pres_appt=staff['PRES_APPT'],
                        station=staff['DIVISION/STATION'], password=passw)
        entries.append(new_entry)
        db.session.add_all(entries)
        db.session.commit()